services:
    bot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        volumes:
            - .:/app
            - ./commands:/app/commands

networks:
    default:
    bridge:
        driver: bridge
